### ISSUE TITLE
Issue with the ::list command

### ISSUE THREAD

**Issue by ColtonMilstead** [DXsmiley/dismock#9]
Thanks for updating the documentation!

However, I'm having this error when I use the ::list command after running a test. 

File "C:\Users\Colton Milstead\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 18-19: character maps to <undefined>

Any thoughts on how to get around this error, or fix it?

**Comment by ColtonMilstead** [comment]
Never mind! Got it to work by placing the below code in the example_test.py main method
------ 
import codecs 
try:
    sys.stdout = codecs.getwriter('utf8')(sys.stdout.buffer)
except:
    sys.stdout = codecs.getwriter('utf8')(sys.stdout)

----

**Comment by dxsmiley** [comment]
Some terminals don't like producing Unicode characters for whatever reason. I've now removed the offending `print` statement from the code, since it was only in there for debugging purposes.
